# This file configures the analyzer for the WE DRIVE customer app.

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    deprecated_member_use: ignore
    unnecessary_null_comparison: ignore
    unnecessary_non_null_assertion: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
