// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEq2IGwJi_Hqgky8vAvz4uja0sVkEdN5Y',
    appId: '1:35696955893:web:48c13d9a517d9136aad0bc',
    messagingSenderId: '35696955893',
    projectId: 'we-drive-4315a',
    authDomain: 'we-drive-4315a.firebaseapp.com',
    storageBucket: 'we-drive-4315a.firebasestorage.app',
    measurementId: 'G-Y8SFT1Y12Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgLN0ArH1ZStJ7kResdM4oS3SWDVx22k',
    appId: '1:35696955893:android:e66408628c9e1b23aad0bc',
    messagingSenderId: '35696955893',
    projectId: 'we-drive-4315a',
    storageBucket: 'we-drive-4315a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVNpjZTDvY1NHbFHzXJxz90YweGtpFnO8',
    appId: '1:35696955893:ios:1116fdeec2abdc30aad0bc',
    messagingSenderId: '35696955893',
    projectId: 'we-drive-4315a',
    storageBucket: 'we-drive-4315a.firebasestorage.app',
    iosBundleId: 'com.example.weDriveV2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVNpjZTDvY1NHbFHzXJxz90YweGtpFnO8',
    appId: '1:35696955893:ios:1116fdeec2abdc30aad0bc',
    messagingSenderId: '35696955893',
    projectId: 'we-drive-4315a',
    storageBucket: 'we-drive-4315a.firebasestorage.app',
    iosBundleId: 'com.example.weDriveV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEq2IGwJi_Hqgky8vAvz4uja0sVkEdN5Y',
    appId: '1:35696955893:web:fe2ffb03170c02cbaad0bc',
    messagingSenderId: '35696955893',
    projectId: 'we-drive-4315a',
    authDomain: 'we-drive-4315a.firebaseapp.com',
    storageBucket: 'we-drive-4315a.firebasestorage.app',
    measurementId: 'G-R6TD2GKD0H',
  );
}
